name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --enable-code-coverage